// packages/inophone-library/tools/catalogue/activities.mjs
// Тема «Занятия» — шесть сцен, 72 понятия.
//
// Сцены этой темы — не помещения, а НАБОРЫ ПРЕДМЕТОВ на общем фоне: транспорт,
// инструменты, животные. Для игры разницы нет (ученик всё так же ищет предмет),
// а для сборки есть: фон таких сцен нейтральный, и всё, что на них видно, —
// это сами объекты. Раскладка поэтому даёт им больше места.

export default {
  id: 'activities',
  titles: {
    ru: 'Занятия', en: 'Activities', fr: 'Activités', de: 'Beschäftigungen', zh: '活动', ba: 'Шөғөлдәр',
  },
  scenes: [
    {
      id: 'transport',
      titles: { ru: 'Транспорт', en: 'Transport', fr: 'Transports', de: 'Verkehr', zh: '交通工具', ba: 'Транспорт' },
      words: [
        { id: 'car',        ru: 'машина',     en: 'car',          fr: 'voiture',      de: 'Auto',         zh: '汽车', ba: 'машина' },
        { id: 'tram',       ru: 'трамвай',    en: 'tram',         fr: 'tramway',      de: 'Straßenbahn',  zh: '有轨电车', ba: 'трамвай' },
        { id: 'trolleybus', ru: 'троллейбус', en: 'trolleybus',   fr: 'trolleybus',   de: 'Oberleitungsbus', zh: '无轨电车', ba: 'троллейбус' },
        { id: 'plane',      ru: 'самолёт',    en: 'aeroplane',    fr: 'avion',        de: 'Flugzeug',     zh: '飞机', ba: 'самолёт' },
        { id: 'helicopter', ru: 'вертолёт',   en: 'helicopter',   fr: 'hélicoptère',  de: 'Hubschrauber', zh: '直升机', ba: 'вертолёт' },
        { id: 'motorcycle', ru: 'мотоцикл',   en: 'motorcycle',   fr: 'moto',         de: 'Motorrad',     zh: '摩托车', ba: 'мотоцикл' },
        { id: 'truck',      ru: 'грузовик',   en: 'lorry',        fr: 'camion',       de: 'Lastwagen',    zh: '卡车', ba: 'йөк машинаһы' },
        { id: 'scooter',    ru: 'самокат',    en: 'scooter',      fr: 'trottinette',  de: 'Roller',       zh: '滑板车', ba: 'самокат' },
        { id: 'wheel',      ru: 'колесо',     en: 'wheel',        fr: 'roue',         de: 'Rad',          zh: '轮子', ba: 'тәгәрмәс' },
        { id: 'steering',   ru: 'руль',       en: 'steering wheel', fr: 'volant',     de: 'Lenkrad',      zh: '方向盘', ba: 'руль' },
        { id: 'sledge',     ru: 'санки',      en: 'sledge',       fr: 'luge',         de: 'Schlitten',    zh: '雪橇', ba: 'сана' },
        { id: 'metro',      ru: 'метро',      en: 'underground',  fr: 'métro',        de: 'U-Bahn',       zh: '地铁', ba: 'метро' },
      ],
    },
    {
      id: 'sport',
      titles: { ru: 'Спорт', en: 'Sport', fr: 'Sport', de: 'Sport', zh: '运动', ba: 'Спорт' },
      words: [
        { id: 'footballball', ru: 'футбольный мяч', en: 'football', fr: 'ballon de foot', de: 'Fußball', zh: '足球', ba: 'футбол тубы' },
        { id: 'goal',       ru: 'ворота',     en: 'goal',         fr: 'but',          de: 'Tor',          zh: '球门', ba: 'ҡапҡа' },
        { id: 'racket',     ru: 'ракетка',    en: 'racket',       fr: 'raquette',     de: 'Schläger',     zh: '球拍', ba: 'ракетка' },
        { id: 'skates',     ru: 'коньки',     en: 'skates',       fr: 'patins',       de: 'Schlittschuhe',zh: '冰鞋', ba: 'тимераяҡ' },
        { id: 'skis',       ru: 'лыжи',       en: 'skis',         fr: 'skis',         de: 'Skier',        zh: '滑雪板', ba: 'саңғы' },
        { id: 'dumbbell',   ru: 'гантель',    en: 'dumbbell',     fr: 'haltère',      de: 'Hantel',       zh: '哑铃', ba: 'гантель' },
        { id: 'skiprope',   ru: 'скакалка',   en: 'skipping rope',fr: 'corde à sauter', de: 'Springseil', zh: '跳绳', ba: 'һикереү бауы' },
        { id: 'medal',      ru: 'медаль',     en: 'medal',        fr: 'médaille',     de: 'Medaille',     zh: '奖牌', ba: 'миҙал' },
        { id: 'cup_prize',   ru: 'кубок',      en: 'trophy',       fr: 'coupe',        de: 'Pokal',        zh: '奖杯', ba: 'кубок' },
        { id: 'whistle',    ru: 'свисток',    en: 'whistle',      fr: 'sifflet',      de: 'Trillerpfeife',zh: '哨子', ba: 'һыҙғырғыс' },
        { id: 'net',        ru: 'сетка',      en: 'net',          fr: 'filet',        de: 'Netz',         zh: '球网', ba: 'сетка' },
        { id: 'stopwatch',  ru: 'секундомер', en: 'stopwatch',    fr: 'chronomètre',  de: 'Stoppuhr',     zh: '秒表', ba: 'секундомер' },
      ],
    },
    {
      id: 'music',
      titles: { ru: 'Музыка', en: 'Music', fr: 'Musique', de: 'Musik', zh: '音乐', ba: 'Музыка' },
      words: [
        { id: 'guitar',     ru: 'гитара',     en: 'guitar',       fr: 'guitare',      de: 'Gitarre',      zh: '吉他', ba: 'гитара' },
        { id: 'piano',      ru: 'пианино',    en: 'piano',        fr: 'piano',        de: 'Klavier',      zh: '钢琴', ba: 'пианино' },
        { id: 'violin',     ru: 'скрипка',    en: 'violin',       fr: 'violon',       de: 'Geige',        zh: '小提琴', ba: 'скрипка' },
        { id: 'drum',       ru: 'барабан',    en: 'drum',         fr: 'tambour',      de: 'Trommel',      zh: '鼓',   ba: 'барабан' },
        { id: 'flute',      ru: 'флейта',     en: 'flute',        fr: 'flûte',        de: 'Flöte',        zh: '长笛', ba: 'ҡурай' },
        { id: 'accordion',  ru: 'гармонь',    en: 'accordion',    fr: 'accordéon',    de: 'Akkordeon',    zh: '手风琴', ba: 'гармун' },
        { id: 'trumpet',    ru: 'труба',      en: 'trumpet',      fr: 'trompette',    de: 'Trompete',     zh: '小号', ba: 'быргы' },
        { id: 'notes',      ru: 'ноты',       en: 'sheet music',  fr: 'partition',    de: 'Noten',        zh: '乐谱', ba: 'ноталар' },
        { id: 'microphone', ru: 'микрофон',   en: 'microphone',   fr: 'microphone',   de: 'Mikrofon',     zh: '麦克风', ba: 'микрофон' },
        { id: 'headphones', ru: 'наушники',   en: 'headphones',   fr: 'casque',       de: 'Kopfhörer',    zh: '耳机', ba: 'наушниктар' },
        { id: 'speaker',    ru: 'колонка',    en: 'loudspeaker',  fr: 'enceinte',     de: 'Lautsprecher', zh: '音箱', ba: 'динамик' },
        { id: 'stage',      ru: 'сцена',      en: 'stage',        fr: 'scène',        de: 'Bühne',        zh: '舞台', ba: 'сәхнә' },
      ],
    },
    {
      id: 'jobs',
      titles: { ru: 'Профессии', en: 'Jobs', fr: 'Métiers', de: 'Berufe', zh: '职业', ba: 'Һөнәрҙәр' },
      words: [
        { id: 'builder',    ru: 'строитель',  en: 'builder',      fr: 'maçon',        de: 'Bauarbeiter',  zh: '建筑工人', ba: 'төҙөүсе' },
        { id: 'driver',     ru: 'водитель',   en: 'driver',       fr: 'chauffeur',    de: 'Fahrer',       zh: '司机', ba: 'водитель' },
        { id: 'cook',       ru: 'повар',      en: 'cook',         fr: 'cuisinier',    de: 'Koch',         zh: '厨师', ba: 'бешеүсе' },
        { id: 'firefighter',ru: 'пожарный',   en: 'firefighter',  fr: 'pompier',      de: 'Feuerwehrmann',zh: '消防员', ba: 'янғын һүндереүсе' },
        { id: 'police',     ru: 'полицейский',en: 'police officer',fr: 'policier',    de: 'Polizist',     zh: '警察', ba: 'полиция хеҙмәткәре' },
        { id: 'postman',    ru: 'почтальон',  en: 'postman',      fr: 'facteur',      de: 'Briefträger',  zh: '邮递员', ba: 'почтальон' },
        { id: 'farmer',     ru: 'фермер',     en: 'farmer',       fr: 'agriculteur',  de: 'Bauer',        zh: '农民', ba: 'фермер' },
        { id: 'pilot',      ru: 'лётчик',     en: 'pilot',        fr: 'pilote',       de: 'Pilot',        zh: '飞行员', ba: 'осоусы' },
        { id: 'hairdresser',ru: 'парикмахер', en: 'hairdresser',  fr: 'coiffeur',     de: 'Friseur',      zh: '理发师', ba: 'сәс алыусы' },
        { id: 'painter_job', ru: 'маляр',      en: 'painter',      fr: 'peintre',      de: 'Maler',        zh: '油漆工', ba: 'буяусы' },
        { id: 'hammer',     ru: 'молоток',    en: 'hammer',       fr: 'marteau',      de: 'Hammer',       zh: '锤子', ba: 'сүкеш' },
        { id: 'saw',        ru: 'пила',       en: 'saw',          fr: 'scie',         de: 'Säge',         zh: '锯子', ba: 'бысҡы' },
      ],
    },
    {
      id: 'supplies',
      titles: { ru: 'Школьные вещи', en: 'School things', fr: 'Fournitures scolaires', de: 'Schulsachen', zh: '文具', ba: 'Мәктәп кәрәк-ярағы' },
      words: [
        { id: 'schoolbag',  ru: 'портфель',   en: 'school bag',   fr: 'cartable',     de: 'Schulranzen',  zh: '书包', ba: 'портфель' },
        { id: 'pencil',     ru: 'карандаш',   en: 'pencil',       fr: 'crayon',       de: 'Bleistift',    zh: '铅笔', ba: 'ҡәләм' },
        { id: 'rubber',     ru: 'ластик',     en: 'eraser',       fr: 'gomme',        de: 'Radiergummi',  zh: '橡皮', ba: 'резинка' },
        { id: 'ruler',      ru: 'линейка',    en: 'ruler',        fr: 'règle',        de: 'Lineal',       zh: '尺子', ba: 'линейка' },
        { id: 'scissors',   ru: 'ножницы',    en: 'scissors',     fr: 'ciseaux',      de: 'Schere',       zh: '剪刀', ba: 'ҡайсы' },
        { id: 'glue',       ru: 'клей',       en: 'glue',         fr: 'colle',        de: 'Klebstoff',    zh: '胶水', ba: 'йәбешкәк' },
        { id: 'paints',     ru: 'краски',     en: 'paints',       fr: 'peintures',    de: 'Farben',       zh: '颜料', ba: 'буяуҙар' },
        { id: 'brush_art',   ru: 'кисточка',   en: 'paintbrush',   fr: 'pinceau',      de: 'Pinsel',       zh: '画笔', ba: 'мылсыҡ' },
        { id: 'pencilcase', ru: 'пенал',      en: 'pencil case',  fr: 'trousse',      de: 'Federmappe',   zh: '文具盒', ba: 'пенал' },
        { id: 'sharpener',  ru: 'точилка',    en: 'sharpener',    fr: 'taille-crayon',de: 'Anspitzer',    zh: '卷笔刀', ba: 'осларғыс' },
        { id: 'diary',      ru: 'дневник',    en: 'school diary', fr: 'carnet de notes', de: 'Hausaufgabenheft', zh: '记事本', ba: 'көндәлек' },
        { id: 'textbook',   ru: 'учебник',    en: 'textbook',     fr: 'manuel',       de: 'Lehrbuch',     zh: '课本', ba: 'дәреслек' },
      ],
    },
    {
      id: 'animals',
      titles: { ru: 'Животные', en: 'Animals', fr: 'Animaux', de: 'Tiere', zh: '动物', ba: 'Хайуандар' },
      words: [
        { id: 'cat',        ru: 'кошка',      en: 'cat',          fr: 'chat',         de: 'Katze',        zh: '猫',   ba: 'бесәй' },
        { id: 'dog',        ru: 'собака',     en: 'dog',          fr: 'chien',        de: 'Hund',         zh: '狗',   ba: 'эт' },
        { id: 'cow',        ru: 'корова',     en: 'cow',          fr: 'vache',        de: 'Kuh',          zh: '牛',   ba: 'һыйыр' },
        { id: 'horse',      ru: 'лошадь',     en: 'horse',        fr: 'cheval',       de: 'Pferd',        zh: '马',   ba: 'ат' },
        { id: 'sheep',      ru: 'овца',       en: 'sheep',        fr: 'mouton',       de: 'Schaf',        zh: '羊',   ba: 'һарыҡ' },
        { id: 'goat_farm',   ru: 'коза',       en: 'goat',         fr: 'chèvre',       de: 'Ziege',        zh: '山羊', ba: 'кәзә' },
        { id: 'hen',        ru: 'курица',     en: 'hen',          fr: 'poule',        de: 'Huhn',         zh: '母鸡', ba: 'тауыҡ' },
        { id: 'goose',      ru: 'гусь',       en: 'goose',        fr: 'oie',          de: 'Gans',         zh: '鹅',   ba: 'ҡаҙ' },
        { id: 'rabbit',     ru: 'кролик',     en: 'rabbit',       fr: 'lapin',        de: 'Kaninchen',    zh: '兔子', ba: 'ҡуян' },
        { id: 'pig',        ru: 'свинья',     en: 'pig',          fr: 'cochon',       de: 'Schwein',      zh: '猪',   ba: 'сусҡа' },
        { id: 'mouse',      ru: 'мышка',      en: 'mouse',        fr: 'souris',       de: 'Maus',         zh: '老鼠', ba: 'сысҡан хайуан' },
        { id: 'bird',       ru: 'птица',      en: 'bird',         fr: 'oiseau',       de: 'Vogel',        zh: '鸟',   ba: 'ҡош' },
      ],
    },
  ],
};
